com.pentaho|pentaho-ee-parent-pom=10.3.0.0-196
com.pentaho|pentaho-ee-jar-parent-pom=10.3.0.0-196
com.pentaho|pentaho-ee-bundle-parent-pom=10.3.0.0-196
org.pentaho|pentaho-parent-pom=10.3.0.0-196
org.pentaho|pentaho-ce-parent-pom=10.3.0.0-196
org.pentaho|pentaho-ce-jar-parent-pom=10.3.0.0-196
org.pentaho|pentaho-ce-bundle-parent-pom=10.3.0.0-196
org.pentaho.di.plugins|pdi-plugins=10.3.0.0-196
com.pentaho.di.plugins|pdi-ee-plugins=10.3.0.0-196

ael.version=10.3.0.0-196
aggdesigner.version=10.3.0.0-196
analysis-ee-plugin.version=10.3.0.0-196
analyzer-plugin.version=10.3.0.0-196
archetypes.version=10.3.0.0-196
big-data-plugin.version=10.3.0.0-196
big-data-kafka-plugin.version=10.3.0.0-196
coding-standards.version=10.3.0.0-196
common-ui.version=10.3.0.0-196
commons-database.version=10.3.0.0-196
commons-ee.version=10.3.0.0-196
commons-gwt.version=10.3.0.0-196
commons-xul.version=10.3.0.0-196
container-utils.version=10.3.0.0-196
dashboard.version=10.3.0.0-196
dashboard-plugin.version=10.3.0.0-196
encryption-support.version=10.3.0.0-196
jdbc-distribution-utility.version=10.3.0.0-196
kafka-plugin.version=10.3.0.0-196
launcher.version=10.3.0.0-196
layout-editor.version=10.3.0.0-196
metadata-client-tool.version=10.3.0.0-196
metastore.version=10.3.0.0-196
mondrian.version=10.3.0.0-196
mondrian-schemaworkbench-plugins.version=10.3.0.0-196
pdi-data-refinery-plugin.version=10.3.0.0-196
pdi-dataservice-client-plugin.version=10.3.0.0-196
pdi-dataservice-plugin.version=10.3.0.0-196
pdi-google-analytics-plugin-ce.version=10.3.0.0-196
pdi-google-analytics-plugin.version=10.3.0.0-196
pdi-hadoop-plugin-ee.version=10.3.0.0-196
pdi-jms-plugin.version=10.3.0.0-196
pdi-monitoring-plugin.version=10.3.0.0-196
pdi-osgi-bridge.version=10.3.0.0-196
pdi-platform-utils-plugin.version=10.3.0.0-196
pdi-plugins-ee.version=10.3.0.0-196
pdi-pur-plugin.version=10.3.0.0-196
pdi-salesforce-plugin.version=10.3.0.0-196
pdi-sap-hana-bulk-loader-plugin.version=10.3.0.0-196
pdi-scheduler-plugin.version=10.3.0.0-196
pdi-spark-plugin.version=10.3.0.0-196
pdi-teradata-tpt-plugin.version=10.3.0.0-196
pdi-weka-plugin-group.version=10.3.0.0-196
pdi-json-plugin.version=10.3.0.0-196
pdi-r-plugin.version=10.3.0.0-196
pdi-sap-plugin.version=10.3.0.0-196
pdi-sdk-plugins.version=10.3.0.0-196
pdi-xml-plugin.version=10.3.0.0-196
pdi.version=10.3.0.0-196
pentaho-actionsequence-dom.version=10.3.0.0-196
pentaho-camel.version=10.3.0.0-196
pentaho-cassandra-plugin.version=10.3.0.0-196
pentaho-ccc-plugin.version=10.3.0.0-196
pentaho-cda-plugin.version=10.3.0.0-196
pentaho-cde-plugin.version=10.3.0.0-196
pentaho-cdf-plugin.version=10.3.0.0-196
pentaho-cgg-plugin.version=10.3.0.0-196
pentaho-chartbeans.version=10.3.0.0-196
pentaho-connections.version=10.3.0.0-196
pentaho-cpf-plugin.version=10.3.0.0-196
pentaho-cpk-plugin.version=10.3.0.0-196
pentaho-dashboard-chart-editor.version=10.3.0.0-196
pentaho-data-access.version=10.3.0.0-196
pentaho-data-mining.version=10.3.0.0-196
pentaho-det.version=10.3.0.0-196
pentaho-ee-chart-plugin.version=10.3.0.0-196
pentaho-ee-dsc.version=10.3.0.0-196
pentaho-ee-license-installer.version=10.3.0.0-196
pentaho-eula-wrap-config.version=10.3.0.0-196
pentaho-geo-plugin.version=10.3.0.0-196
pentaho-hadoop-shims.version=10.3.0.0-196
pentaho-hadoop-shims-api.version=10.3.0.0-196
pentaho-hadoop-shims-cdh513.version=10.3.0.0-196
pentaho-hadoop-shims-cdh514.version=10.3.0.0-196
pentaho-hadoop-shims-cdh61.version=10.3.0.0-196
pentaho-hadoop-shims-cdpdc71.version=10.3.0.0-196
pentaho-hadoop-shims-dataproc1421.version=10.3.0.0-196
pentaho-hadoop-shims-emr511.version=10.3.0.0-196
pentaho-hadoop-shims-emr521.version=10.3.0.0-196
pentaho-hadoop-shims-hdp26.version=10.3.0.0-196
pentaho-hadoop-shims-hdp30.version=10.3.0.0-196
pentaho-hadoop-shims-mapr520.version=10.3.0.0-196
pentaho-hadoop-shims-mapr60.version=10.3.0.0-196
pentaho-hadoop-shims-mapr61.version=10.3.0.0-196
pentaho-hadoop-shims-hdi40.version=10.3.0.0-196
pentaho-hdfs-vfs.version=10.3.0.0-196
pentaho-jpivot-plugin.version=10.3.0.0-196
pentaho-json.version=10.3.0.0-196
pentaho-kettle-yarn-plugin.version=10.3.0.0-196
pentaho-karaf.version=10.3.0.0-196
pentaho-launcher.version=10.3.0.0-196
pentaho-marketplace-modules.version=10.3.0.0-196
pentaho-metadata.version=10.3.0.0-196
pentaho-metastore.version=10.3.0.0-196
pentaho-metaverse.version=10.3.0.0-196
pentaho-modeler.version=10.3.0.0-196
pentaho-mongo-utils.version=10.3.0.0-196
pentaho-mongodb-plugin.version=10.3.0.0-196
pentaho-mql-editor.version=10.3.0.0-196
pentaho-operations-mart.version=10.3.0.0-196
pentaho-osgi-bundles.version=10.3.0.0-196
pentaho-palo-core.version=10.3.0.0-196
pentaho-pdi-ee-plugin.version=10.3.0.0-196
pentaho-pdi-plugin.version=10.3.0.0-196
pentaho-r-plugin.version=10.3.0.0-196
pentaho-registry.version=10.3.0.0-196
pentaho-report-wizard-core.version=10.3.0.0-196
pentaho-reporting-plugin.version=10.3.0.0-196
pentaho-reporting.version=10.3.0.0-196
pentaho-repository.version=10.3.0.0-196
pentaho-s3-vfs.version=10.3.0.0-196
pentaho-sparkl-plugin.version=10.3.0.0-196
pentaho-splunk-plugin.version=10.3.0.0-196
pentaho-versionchecker.version=10.3.0.0-196
pentaho-vfs-browser.version=10.3.0.0-196
pentaho.version=10.3.0.0-196
pir-plugin.version=10.3.0.0-196
platform.version=10.3.0.0-196
schemaworkbench-plugins.version=10.3.0.0-196
vertica-bulkloader-plugin.version=10.3.0.0-196
worker-nodes.version=10.3.0.0-196
worker-nodes-custom-resources.version=10.3.0.0-196
hierarchical-plugin-ee.version=10.3.0.0-196

docker.image.tag=9.3-latest
pentaho-cwm.version=1.5.4
pentaho-ofc4j.version=1.1.0
proguard.version=7.1.0
weka-jri.version=5.1.0

version-merger.version=1.0.9
