name: pentaho-generic-file-system scheduled merge workflow

on:
  schedule:
    - cron: "0 0 */4 * *"

jobs:
  reusable-merge-workflow:
    uses: pentaho/actions-common/.github/workflows/merge.yml@PAS
    with:
      base_version: ""
      base_build_name: "pdia-master"
      slack_channels: "milf_builds"
      sonar_project_key: "pentaho-generic-file-system"
      modules_to_build: "."
      run_release_candidate: true
      add_github_run_number: false
      use_semver_release_candidate: true
    secrets: inherit
