name: pentaho-generic-file-system release workflow
on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
        description: "Dry run. No real changes should occur."
      base_version:
        required: false
        description: "The base version to use for the merge."

jobs:
  reusable-merge-workflow:
    uses: pentaho/actions-common/.github/workflows/merge.yml@stable
    with:
      base_version: ${{ inputs.base_version != '' && inputs.base_version || '11.0.0.0-24' }}
      slack_channels: ""
      sonar_project_key: "pentaho-generic-file-system"
      modules_to_build: "."
      run_release_candidate: true
      run_snapshot: false
      add_github_run_number: false
      use_semver_release_candidate: false
    secrets: inherit

  release:
    needs: [ reusable-merge-workflow ]
    uses: pentaho/actions-common/.github/workflows/release.yml@stable
    with:
      release_version: ${{ needs.reusable-merge-workflow.outputs.current-version }}
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit

  update-version:
    needs: [ release ]
    uses: ./.github/workflows/update-version.yml
    with:
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit
